version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_NAME=banco_pifio
      - DB_USER=root
      - DB_PASSWORD=0704
      - DB_HOST=db
      - DB_PORT=3306

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: banco_pifio
      MYSQL_ROOT_PASSWORD: "0704"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
